import 'globals.dart';

String signInString = lang=='en'?'SIGN IN':'ĐĂNG NHẬP';
String signUPString = lang=='en'?'SIGN UP':'ĐĂNG KÝ';
String emailString = 'E-Mail';
String passWordString = lang=='en'?'Password':"Mật khẩu";
String forgotPassString = lang=='en'?"Forgot Password ?" : "Quên mật khẩu ?";
String connectWithString = lang=='en'?"Or connect with":"Hoặc đăng nhập qua";
String doNotHaveAccountString = lang=='en'?"Don't have an account? ":"Chưa có tài khoản?";
String signUpString = lang=='en'?'Sign up': 'Đăng ký';
String nameString = lang=='en'?'Name':'Tên';
String haveAccountString = lang=='en'?"Have an account? ":"Đã có tài khoản?";
String signINString = lang=='en'?'Sign in': 'Đăng nhập';
String passDescription = lang=='en'?'If you need help resetting your password, we can help by sending you a link to reset it.':
    'Nếu bạn muốn đặt lại mật khẩu, chúng tôi có thể gửi link đặt lại mật khẩu cho bạn.';
String sentString = lang=='en'?'SENT':'GỬI';
String enterPhoneNumberString = lang=='en'?'To continue enter your phone number':'Để tiếp tục hãy nhập số điện thoại';
String phoneString = lang=='en'?'Phone':'SĐT';
String continueString = lang=='en'?'CONTINUE':'TIẾP TỤC';
String verifyNumberString = lang=='en'?'Verify phone number':'Xác nhận số điện thoại';
String resentCodeString = lang=='en'?'Resent Code':'Gửi lại mã';
String verifyDoneString = lang=='en'?'Verify Done!':'Xác nhận hoàn tất!';
String haveGoodExperienceString = lang=='en'?'Have a good experrience with our app!':'Chúc bạn có những trải nghiệm tốt với ứng dụng của chúng tôi';
String doneString = lang=='en'?'Done':'Hoàn tất';
String homeString = lang=='en'?'Home':'Trang chủ';
String exploreString = lang=='en'?'Explore':'Khám phá';
String radioString = "Radio";
String accountString = lang=='en'?'Account':'Tài khoản';
String newAlbumString = lang=='en'?'New Albums':'Album mới';
String viewAllString = lang=='en'?'View all':'Xem tất cả';
String recentMusicString = lang=='en'?'Recently Music':'Gần đây';
String chartString = lang=='en'?'Chart':'Bảng xếp hạng';
String topicString = lang=='en'?'Topic':'Chủ đề';
String searchString = lang=='en'?'Search':'Tìm kiếm';
String cancelString = lang=='en'?'Cancel':'Huỷ bỏ';
String historyString = lang=='en'?'History':'Lịch sử';
String topSearchString = lang=='en'?'Top Searching':'Tìm kiếm nhiều nhất';
String allString = lang=='en'?'All':'Tất cả';
String songString = lang=='en'?'Song':'Bài hát';
String artistString = lang=='en'?'Artist':'Nghệ sĩ';
String albumString = 'Album';
String showMoreString = "Show more";
String suggestionsString = "Suggestions";
String lyricString = "Lyrics";